### ISSUE TITLE
Sentinel 2 images for split tiles only shows the /0 folder only, not the /1

### ISSUE THREAD

**Issue by hareldunn** [RemotePixel/satellitesearch#5]
Some S2 tiles for specific dates are split into two separate images. 
![image](https://user-images.githubusercontent.com/24369355/31514771-7772a7ee-af9b-11e7-8243-09145fdf48c5.png)
In such cases, only the first image - the [/0](http://sentinel-s2-l1c.s3-website.eu-central-1.amazonaws.com/#tiles/36/R/YV/2016/10/3/0/) - appears in the search results, but not the [/1](http://sentinel-s2-l1c.s3-website.eu-central-1.amazonaws.com/#tiles/36/R/YV/2016/10/3/1/). in the example above, most of the image ended up in /1 folder which was not shown, and will not be downloaded from thr direct download link.

**Comment by vincentsarago** [comment]
Thanks for opening the issue @hareldunn ;-) 
I'll try to see what we can do here

**Comment by vincentsarago** [comment]
@hareldunn this is not something I could fix on my side. The bug appears to be on with the API satellite search rely on. 
I've opened an issue and I'll work with devseed team to fix it https://github.com/sat-utils/sat-api/issues/26
